/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package m39.m81.m213.m129.models;

import java.util.*;

public class GetCalculateOppInputBuilder {
    //the instance to build
    private GetCalculateOppInput getCalculateOppInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCalculateOppInputBuilder() {
        getCalculateOppInput = new GetCalculateOppInput();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCalculateOppInputBuilder operation(OperationTypeEnum operation) {
        getCalculateOppInput.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCalculateOppInputBuilder x(double x) {
        getCalculateOppInput.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCalculateOppInputBuilder y(double y) {
        getCalculateOppInput.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCalculateOppInput build() {
        return getCalculateOppInput;
    }
}