/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package m39.m81.m213.m129.models;

import java.util.*;

public class GetCalculateBarcelonaAPIMeetupInputBuilder {
    //the instance to build
    private GetCalculateBarcelonaAPIMeetupInput getCalculateBarcelonaAPIMeetupInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCalculateBarcelonaAPIMeetupInputBuilder() {
        getCalculateBarcelonaAPIMeetupInput = new GetCalculateBarcelonaAPIMeetupInput();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCalculateBarcelonaAPIMeetupInputBuilder operation(OperationTypeEnum operation) {
        getCalculateBarcelonaAPIMeetupInput.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCalculateBarcelonaAPIMeetupInputBuilder x(double x) {
        getCalculateBarcelonaAPIMeetupInput.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCalculateBarcelonaAPIMeetupInputBuilder y(double y) {
        getCalculateBarcelonaAPIMeetupInput.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCalculateBarcelonaAPIMeetupInput build() {
        return getCalculateBarcelonaAPIMeetupInput;
    }
}